name: example
description: Flutter Cupertino Birthday Textbox Example
version: 1.0.1


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.11.0"

dependencies:
  cupertino_date_textbox:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
